# docker-compose.yml
services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
    volumes:
      - ./wg-zimmer-listings:/app/wg-zimmer-listings
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /Users/felix/.config/gcloud:/root/.config/gcloud:ro
    network_mode: host
